name: Build Tool - Tester
on:
  workflow_dispatch:
    inputs:
      skip:
        description: Templates to skip
        required: false
        default: ""
      require:
        description: Templates required to run
        required: false
        default: ""
      files:
        description: Specific JSON files to test
        required: false
        default: ""
      gitRef:
        description: Github reference to test
        required: true
        default: "refs/heads/v3"

env:
  TAG: templatetester
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-tool:
    name: Build Tool
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platform: [ "linux/amd64" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,${{ env.TAG }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: Dockerfile-${{ env.TAG }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            sha: ${{ github.sha }}
            version: ${{ env.VERSION }}
          platforms: ${{ matrix.platform }}

  run-tester:
    name: Run Tool
    runs-on: template-tester
    permissions:
      packages: read

    needs:
      - build-tool

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker rm -f templatetester || true
          echo "::add-mask::${{ secrets.RUNNER_IP }}"
          docker run --rm --name templatetester --network host -v /var/run/docker.sock:/var/run/docker.sock ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} --gitRef=${{ inputs.gitRef }} --workDir=/tmp/pufferpanel-tester --skip=${{ inputs.skip }} --require=${{ inputs.require }} --files=${{ inputs.files }}